spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${S2_DB_HOST:10.0.12.252}:${S2_DB_PORT:5438}/${S2_DB_DATABASE:supersonic}?stringtype=unspecified
    username: ${S2_DB_USER:metricsys}
    password: ${S2_DB_PASSWORD:postgres}
  sql:
    init:
      continue-on-error: true
      mode: always
      username: ${S2_DB_USER:metricsys}
      password: ${S2_DB_PASSWORD:postgres}
      schema-locations: classpath:db/schema-postgres.sql,classpath:db/schema-postgres-demo.sql
      data-locations: classpath:db/data-postgres.sql,classpath:db/data-postgres-demo.sql

s2:
  embedding:
    store:
      provider: PGVECTOR
      base:
        url: ${S2_DB_HOST:10.0.12.252}
      port: ${S2_DB_PORT:5438}
      databaseName: ${S2_DB_DATABASE:supersonic}
      user: ${S2_DB_USER:metricsys}
      password: ${S2_DB_PASSWORD:postgres}
      dimension: 512
